#!/bin/sh

# Default layout (can be bsp, stack or float)
yabai -m config layout stack

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

yabai -m config top_padding    0
yabai -m config bottom_padding 0
yabai -m config left_padding   0
yabai -m config right_padding  0
yabai -m config window_gap     0

# Disable window tiling for the following apps
yabai -m rule --add app="^System Settings$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^QuickTime Player$" sticky=on manage=off
