"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

command_timeout=1000

[aws]
disabled = true

[lua]
disabled = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[docker_context]
disabled = true

[git_branch]
format = 'on [$symbol$branch]($style) '

[c]
symbol = " "
style = "bold blue"

[custom.nvim]
command = "nvim --version | head -n 1 | cut -d ' ' -f 2"
symbol = ""
when = "pwd | grep -q '/nvim'"
format = "[$symbol](green) $output "

[custom.npm]
symbol = ""
detect_files = ["package-lock.json"]
format = "[$symbol](red) "

[custom.pnpm]
symbol = ""
detect_files = ["pnpm-lock.yaml", "pnpm-workspace.yaml"]
format = "[$symbol](yellow) "

[custom.yarn]
symbol = ""
detect_files = ["yarn.lock"]
format = "[$symbol](blue) "

