# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

command_timeout=1000

[aws]
disabled = true

[lua]
disabled = true

[character]
# Replace the '❯' symbol in the prompt with '➜'
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[docker_context]
disabled = true # Enable if they support docker version

[git_branch]
format = 'on [$symbol$branch]($style) '

[custom.nvim]
command = "nvim --version | head -n 1 | cut -d ' ' -f 2"
symbol = ""
when = "pwd | grep -q '/nvim'"
format = "[$symbol](green) $output "

