# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character]
# Replace the '❯' symbol in the prompt with '➜'
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[docker_context]
disabled = true # Enable if they support docker version

[git_branch]
format = 'on [$symbol$branch]($style) '